# ----------------------------------------------------------
# Configuration
# ----------------------------------------------------------
  baseURL = 'https://example.com/'
  languageCode = 'en'
  title = 'Site Name'
  copyright = '2023 Site Name'
  publishDir = 'public'
  enableInlineShortcodes = true
  disableHugoGeneratorInject = true
  disableKinds = ['rss', 'sitemap']

# ----------------------------------------------------------
# Parameters (see params.toml for CSS variable parameters)
# - rss_feed requires 'rss' removed from disableKinds above. 
# - theme_switch also needs to be enabled in staticstart.scss.
# - js_footer needs to be true for js_menu and/or js_dialog.
# ----------------------------------------------------------
  [params]
  
  description = 'StaticStart is a blank, ready-to-build Hugo static website template with customisable CSS.'
  author = 'Author Name'
  email = "mailto:author@example.com"
  twitter = "https://twitter.com/authorname"
  mastodon = "https://mastodon.social/@authorname"
  github = "https://github.com/authorsname"
  banner = "/banner.png"
  social_meta = 'false'
  rss_feed = 'false'  
  theme_switch = 'true'  
  js_footer = 'true'
  js_menu = 'false'
  js_dialog = 'true'
  css_standard = 'true'
  css_minify = 'false'
  css_inline = 'false'

# ----------------------------------------------------------
# Menus
# ----------------------------------------------------------  
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = -1

# ----------------------------------------------------------
# Taxonomy
# ----------------------------------------------------------
  [taxonomies]
    tags = 'tags'

# ----------------------------------------------------------
# Markup
# - typographer disables curly quotes in summaries.
# - unsafe allows writing HTML in MD documents.
# - autoHeadingID disables TOC auto-IDs for MD headings.
# - noClasses allows custom Chroma syntax highlighting.
# ----------------------------------------------------------
  [markup]
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false  
                   
    [markup.goldmark.renderer]
      unsafe = true        
      
    [markup.goldmark.parser]
      autoHeadingID = false
      
    [markup.highlight]
      noClasses = false

# ----------------------------------------------------------
# Minify HTML
# ----------------------------------------------------------
  [minify]
    minifyOutput = false