# ----------------------------------------------------------
# Configuration
# ----------------------------------------------------------
  baseURL = 'https://pmbrown.net/'
  languageCode = 'en-au'
  title = 'StaticStart'
  copyright = '2023 Phil Brown'
  publishDir = 'website'
  enableInlineShortcodes = true
  disableHugoGeneratorInject = true
  disableKinds = ['rss', 'sitemap']

# ----------------------------------------------------------
# Parameters (see params.toml for CSS parameters)
# - rss_feed requires 'rss' removed from disableKinds above. 
# - theme_switch also needs to be enabled in staticstart.scss.
# - js_footer needs to be true for js_menu and/or js_dialog.
# ----------------------------------------------------------
  [params]
  
  description = 'A blank, ready-to-build Hugo static website template with customisable CSS.'
  author = 'Phil Brown'
  email = "mailto:philbrown.webdev@gmail.com"
  twitter = "https://twitter.com/philbrownweb"
  mastodon = "https://techhub.social/@philbrown"
  github = "https://github.com/pmbrown"
  banner = "/banner.png"
  social_meta = 'false'
  rss_feed = 'false'  
  theme_switch = 'true'  
  js_footer = 'true'
  js_menu = 'false'
  js_dialog = 'true'

# ----------------------------------------------------------
# Menus
# ----------------------------------------------------------  
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = 1

# ----------------------------------------------------------
# Taxonomy (disabled by default)
# ----------------------------------------------------------
  [taxonomies]
#   tags = 'tags'

# ----------------------------------------------------------
# Markup
# - typographer disables curly quotes in summaries.
# - unsafe allows writing HTML in MD documents.
# - autoHeadingID disables TOC auto-IDs for MD headings.
# - noClasses allows custom Chroma syntax highlighting.
# ----------------------------------------------------------
  [markup]
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false  
                   
    [markup.goldmark.renderer]
      unsafe = true        
      
    [markup.goldmark.parser]
      autoHeadingID = false
      
    [markup.highlight]
      noClasses = false

# ----------------------------------------------------------
# Minify HTML (see params.toml for CSS minify options)
# ----------------------------------------------------------
  [minify]
    minifyOutput = false