# ----------------------------------------------------------
# Menus
# ----------------------------------------------------------


[[main]]
  identifier = 'home'
  title = 'Home'
  url = '/'
  weight = -1