# ----------------------------------------------------------
# CSS variables
# ---------------------------------------------------------- 
  [style]

# ---------------------------------------------------------- 
# Brand and theme
# Change hue and saturation values to alter brand color and
# theme color-schemes globally, adjust lightness values in
# individual color-schemes below to suit.
# ----------------------------------------------------------  
  brand-hs = '40 99%'
  theme-hs = '0 0%'

# ---------------------------------------------------------- 
# Light color-scheme
# ----------------------------------------------------------
  text-light = 'hsl(var(--theme-hs) 20%)'
  link-light = '#1c3db5'
  link-hover-light = 'color-mix(in srgb, var(--link) 60%, white)'
  body-bg-light = 'hsl(var(--theme-hs) 99%)'
  surf-1-light = 'hsl(var(--theme-hs) 94%)'
  surf-2-light = 'hsl(var(--theme-hs) 87%)'
  surf-3-light = 'hsl(var(--theme-hs) 81%)'
  surf-4-light = 'hsl(var(--theme-hs) 71%)'
  brand-light = 'hsl(var(--brand-hs) 42%)'

# ---------------------------------------------------------- 
# Dark color-scheme
# ---------------------------------------------------------- 
  text-dark = 'hsl(var(--theme-hs) 99%)'
  link-dark = '#9fbfdf'
  link-hover-dark = 'color-mix(in srgb, var(--link) 75%, white)'
  body-bg-dark = 'hsl(var(--theme-hs) 14%)'
  surf-1-dark = 'hsl(var(--theme-hs) 18%)'
  surf-2-dark = 'hsl(var(--theme-hs) 24%)'
  surf-3-dark = 'hsl(var(--theme-hs) 31%)'
  surf-4-dark = 'hsl(var(--theme-hs) 41%)'
  brand-dark = 'hsl(var(--brand-hs) 48%)'

# ---------------------------------------------------------- 
# Primary colors
# Use *-hs values for tints/shades.
# Use *-hsl values for alpha channels 
# ---------------------------------------------------------- 
  blue = '#264d73'
  blue-hs = '210 50%'
  blue-hsl = 'var(--blue-hs) 30%'
  red = '#9a1d1d'
  red-hs = '0 68%'
  red-hsl = 'var(--red-hs) 36%'
  green = '#2b6020'
  green-hs = '110 50%'
  green-hsl = 'var(--green-hs) 25%'
  orange = '#ffc14d'
  orange-hs = '39 100%'
  orange-hsl = 'var(--orange-hs) 65%'
  cyan = '#00e6e6'
  cyan-hs = '180 100%'
  cyan-hsl = 'var(--cyan-hs) 45%'
# ----------------------------------------------------------

# ---------------------------------------------------------- 
# Typography
# ---------------------------------------------------------- 
  font_family = 'system-ui, -apple-system, Arial, Helvetica, sans-serif'
  font_size_page = 'clamp(100%, 40% + 0.666vw, 140%)'
  body = '1rem'
  lg = '1.1rem'
  lgr = '1.25rem'
  sm = '0.906rem'
  sml = '0.813rem'
  xs = '0.75rem'
  h1 = '2rem'
  h2 = '1.725rem'
  h3 = '1.5rem'
  h4 = '1.35rem'
  h5 = '1.2rem'
  h6 = '1.063rem'
  lh-body = '1.5'
  lh-header = '1.2'
  lh-btn-forms = '1.4'

# ---------------------------------------------------------- 
# Buttons and forms
# ---------------------------------------------------------- 
  btn-pb = '0.25rem'
  btn-pi = '0.75rem'
  btn-bg = 'var(--surf-1)'
  btn-hover = 'var(--surf-2)'
  btn-border = '1px'
  btn-border-color = 'var(--surf-2)'
  btn-radius = '0.125em'
  form-pb = '0.25rem'
  form-pi = '0.5rem'
  form-bg = 'var(--body-bg)'
  form-border = '1px'
  form-border-color = 'var(--surf-3)'
  form-radius = '0.125em'
  input-focus = '0 0 0 0.12rem'
  input-focus-color = 'var(--surf-3)'

# ---------------------------------------------------------- 
# Tables
# ---------------------------------------------------------- 
  table-thead-txt = 'var(--text)'
  table-thead-bg = 'var(--surf-1)'
  table-hover = 'color-mix(in srgb, var(--table-thead-bg) 55%, var(--body-bg))'
  table-stripes = 'color-mix(in srgb, var(--table-thead-bg) 35%, var(--body-bg))'
  table-border-color = 'var(--surf-2)'
  table-border-width = '0.0125rem'
  table-pb = '0.25rem'
  table-pi = '0.65rem'
  table-mb = '1rem'

# ---------------------------------------------------------- 
# Grid and page breakpoints (plus max-width if used)
# ---------------------------------------------------------- 
  max-page-width = '50rem'
  breakpoint-xl = '1401px'
  breakpoint-lg = '1025px'
  breakpoint-md = '801px'
  breakpoint-sm = '480px'

# ---------------------------------------------------------- 
# Box shadows
# ---------------------------------------------------------- 
  shadow-sm = '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)'
  shadow = '0 0.25rem .75rem rgba(0, 0, 0, 0.15)'
  shadow-lg = '0 0.5rem 1.25rem rgba(0, 0, 0, 0.15)'
